workflows:
  build-expo-apk:
    name: Build Expo APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Expo APK
        script: |
          npm install -g expo-cli eas-cli
          eas build -p android --profile preview --local --non-interactive
    artifacts:
      - build//*.apk
    publishing:
      email:
        recipients:
          - contact.saad0101@gmail.com